# Panopti configuration file

title = "Panopti"

[viewer.tools]
grid.enabled = true
axes.enabled = true

[viewer.renderer]
max-fps = 60
power-preference = "default"
tone-mapping = "linear"
tone-mapping-exposure = 1.0

# Custom lights
light-key     = { type = "directional", position = [10, 15, 10], target = [0, 0, 0], color = "#ffffff", intensity = 2.3, castShadow = false }
light-fill    = { type = "directional", position = [-20, 5, -10], target = [0, 0, 0], color = "#ffffff", intensity = 2.0, castShadow = false }
light-ambient = { type = "ambient", color = "#ffffff", intensity = 1.0 }

[viewer.theme]
primary-color = "#18c37e"
primary-hover = "#25d790"
secondary-color = "#4aa8ff"
background-color = "#f3f6fa"
background-color-dark = "#0b1118"
panel-bg = "#101822"
text-color = "#e8eff8"
text-secondary = "#99a9be"
border-color = "#2a3647"
success-color = "#20ca84"
success-hover = "#2add95"
dark-mode = true

[viewer.camera]
position = [5, 5, 5]
target = [0, 0, 0]
fov = 50
near = 0.1
far = 1000
projection = "perspective"

[viewer.ui]
panel.controls.collapsed = false
panel.layers.collapsed = false
console.enabled = false
infobar.enabled = true

# Viewer settings (low-level, see constants.js):
[viewer.debounce]
slider = 25
transform = 25
camera = 25
